### ISSUE TITLE
Display date in hebrew format

### ISSUE THREAD

**Issue by itaishmida** [hebcal/hdate#2]
Sorry, I cannot find any documentation regarding how to display hebrew date

I want my text to display today, for example - instead of:
19 Elul 5784
display:
י"ט אלול תשפ"ד

I have tried also using:
Locale.useLocale("he");
but I still get the date in english
Is there sa way to displate hebrew dates?

**Comment by mjradwin** [comment]
Try hdate.renderGematriya()

https://hebcal.github.io/api/hdate/classes/HDate.html#renderGematriya

**Comment by itaishmida** [comment]
wow, that is amazing @mjradwin - thank you so much
now I have another request, if I can ask

I need to get the date according to the 'Shkia' of the day
So for example, now in jerusalem time is 20:08, Shkia has passed so date of 22/09/2024 should be after shkia כ אלול תשפד 
Is there a way to get the date like that?

**Comment by mjradwin** [comment]
An instance of `HDate` encapsulates a date in the Hebrew calendar system. It consists of a year, month, and day, without any associated time or location data. The API is intentionally designed to keep the `HDate` class simple. It is a deliberate choice for `HDate` to store only a day, month and year and not have any complexity of time of day or location.

To take location into consideration and get the current `HDate`, try using this function instead:

https://hebcal.github.io/api/core/classes/Zmanim.html#makeSunsetAwareHDate
